plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
    id 'fabric-loom' version '1.17.13'
}

group = 'com.groupdev'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    def fabricLanguageKotlin = modImplementation("net.fabricmc:fabric-language-kotlin:1.13.8+kotlin.2.3.0")
    include fabricLanguageKotlin
}

sourceSets {
    main {
        kotlin.srcDirs = ['src/main/kotlin']
        resources.srcDirs = ['src/main/resources']
    }
}

kotlin {
    jvmToolchain(21)
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

jar {
    archiveBaseName = 'cherry-client'
    manifest {
        attributes(
            'Implementation-Title': 'Cherry Client',
            'Implementation-Version': project.version
        )
    }
}
